Repository higherkindness/compendium, pull requests merged in 2020-03, with the labels that each got.

#229 Mergify: Merge minors when they are approved by one collaborator
  .mergify.yml
  README.md
Labels: devops, improvement

#241 Update to Scala 2.13.1
  .travis.yml
  Dockerfile
  build.sbt
  project/plugins.sbt
Labels: update-dependencies

#244 Set up microsite
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: devops, doc

#240 OpenAPI docs
  src/main/resources/compendium.yaml
Labels: doc

#245 Ignore CI workflow on master branch for now
  .github/workflows/ci.yaml
Labels: devops, improvement

#237 Sbt plugin section
  docs/docs/docs/sbt/index.md
  docs/src/main/resources/microsite/data/menu.yml
Labels: doc

#247 Execute CI workflow for external PRs and add check to Mergify
  .github/workflows/ci.yaml
  .mergify.yml
Labels: devops, improvement

#239 Use GitHub Actions I: Compilation and tests
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .mergify.yml
  .travis.yml
  build.sbt
Labels: devops
